### ISSUE TITLE
Timeout in WPASupplicant

### ISSUE THREAD

**Issue by ConnorRigby** [nerves-networking/vintage_net_wifi#243]
We received this error on a device in the field. Recently called `quick_configure/2`

```
2024-06-10 08:54:28.991 [error] fw doesn't support 11ax

2024-06-10 08:54:28.999 [info] RouteManager: set_connection_status wlan0 -> :lan (ifup)

2024-06-10 08:54:29.002 [info] IPv6: ADDRCONF(NETDEV_CHANGE): wlan0: link becomes ready

2024-06-10 08:54:30.274 [info] mdns_lite wlan0/{65152, 0, 0, 0, 11835, 28927, 65249, 15031}

2024-06-10 08:54:32.944 [warn] Ignoring error getting info on BSSID "5c:64:8e:b8:40:4e": :timeout

2024-06-10 08:54:33.799 [warn] Ignoring error getting info on BSSID "2c:3b:70:e1:3a:b7": :unknown

2024-06-10 08:54:47.803 [error] Task #PID<0.3457559.0> started from #PID<0.3174.0> terminating
** (stop) exited in: GenServer.call({:via, Registry, {VintageNet.Interface.Registry, {VintageNetWiFi.WPASupplicant, "wlan0"}}}, :scan, 5000)
    ** (EXIT) time out
    (elixir 1.15.7) lib/gen_server.ex:1074: GenServer.call/3
    (vintage_net 0.13.5) lib/vintage_net/interface.ex:733: VintageNet.Interface.run_ioctl_and_report/2
    (elixir 1.15.7) lib/task/supervised.ex:101: Task.Supervised.invoke_mfa/2
Function: #Function<5.4329529/0 in VintageNet.Interface.run_ioctl/3>
    Args: []
```

**Comment by ConnorRigby** [comment]
This seems to come from running `quick_configure/2` multiple times in a row without waiting for the configuration to complete. The timeout *seems* to come from when the wpa server is going down and being brought back up.

**Comment by fhunleth** [comment]
Closing since I think this is resolved and if it comes back, maybe there's a nicer way to give the error message.
